### ISSUE TITLE
How to pls...

### ISSUE THREAD

**Issue by Solarkoid** [Pupix/lol-wad-parser#15]
I did everything. Installed every dependency and still when i go in node.js from terminal while both are open i get this when i do commands: 
var WadParser = require('lol-wad-parser'),
[...] wad = new WadParser();
 Error: Cannot find the module 'lol-wad-parser' 
at [...]

pls at least do a tutorial on how to run it... ;=; its just not fair for rito to block all the splash arts from us

**Comment by Pupix** [comment]
Hello,
The `README` file properly explains how to make use of this node.js module. If you have problems following it that means you gotta take a step back and [check out how npm and node.js actually work](https://docs.npmjs.com/getting-started/installing-npm-packages-locally).

I am going to close this since it's not a problem I can actually fix.

Cheers
