### ISSUE TITLE
update

### ISSUE THREAD

**Issue by boditibor** [Pupix/lol-wad-parser#23]
Hi, is there any chance, that you will be working on this project again? It seems not to be working at the moment.

**Comment by Pupix** [comment]
Haven't tested it in a while but it should still work AFAIK. What error are you getting?

**Comment by Pupix** [comment]
I just tested it and it's working fine 🤷‍♂️  
![image](https://user-images.githubusercontent.com/4929965/45934178-b5288300-bf9a-11e8-8b42-8e414a9cfe60.png)

**Comment by boditibor** [comment]
I tried to use it for the first time. I tried to extract Kayn.en_EN.wad.client file, 6 files were extracted without extension, with simiar names to your files.

**Comment by alterlove** [comment]
Can u stop mention all?

Enviado desde mi iPhone

**Comment by Pupix** [comment]
Idk what were you expecting it to do, becauase that's exactly what's supposed to happen. Those are the hash of the files because not all of them are mapped and the extensions are added adhoc via [magic header](https://en.wikipedia.org/wiki/Magic_number_(programming)).

You can find the list of known hashes [here](https://github.com/Pupix/lol-wad-parser/tree/master/hashes/league_client). PR to add more are always welcome.

I'll close this as there's not really an issue.
